<?= $this->doctype() ?>
<?php 
    if(defined('RUNNING_FROM_ROOT')){
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    }
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/angular.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar  navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/lease-web.svg') ?>" height="28" alt="LeaseWeb <?= \Application\Module::VERSION ?>"/>&nbsp;LeaseWeb Servers
                    </a>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
