<style type="text/css">
body {
  padding: 100px;
}

.range {
  position: relative;
  width: 1000px;
  height: 5px;
}

.range input {
  width: 100%;
  position: absolute;
  top: 2px;
  height: 0;
  -webkit-appearance: none;
}
.range input::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 18px;
  height: 18px;
  margin: -8px 0  0;
  border-radius: 50%;
  background: #37adbf;
  cursor: pointer;
  border: 0 !important;
}
.range input::-moz-range-thumb {
  width: 18px;
  height: 18px;
  margin: -8px 0  0;
  border-radius: 50%;
  background: #37adbf;
  cursor: pointer;
  border: 0 !important;
}
.range input::-ms-thumb {
  width: 18px;
  height: 18px;
  margin: -8px 0  0;
  border-radius: 50%;
  background: #37adbf;
  cursor: pointer;
  border: 0 !important;
}
.range input::-webkit-slider-runnable-track {
  width: 100%;
  height: 2px;
  cursor: pointer;
  background: #b2b2b2;
}
.range input::-moz-range-track {
  width: 100%;
  height: 2px;
  cursor: pointer;
  background: #b2b2b2;
}
.range input::-ms-track {
  width: 100%;
  height: 2px;
  cursor: pointer;
  background: #b2b2b2;
}
.range input:focus {
  background: none;
  outline: none;
}
.range input::-ms-track {
  width: 100%;
  cursor: pointer;
  background: transparent;
  border-color: transparent;
  color: transparent;
}

.range-labels {
  margin: 18px -41px 0;
  padding: 0;
  list-style: none;
}
.range-labels li {
  position: relative;
  float: left;
  width: 90.25px;
  text-align: center;
  color: #b2b2b2;
  font-size: 14px;
  cursor: pointer;
}
.range-labels li::before {
  position: absolute;
  top: -25px;
  right: 0;
  left: 0;
  content: "";
  margin: 0 auto;
  width: 9px;
  height: 9px;
  background: #b2b2b2;
  border-radius: 50%;
}
.range-labels .active {
  color: #37adbf;
}
.range-labels .selected::before {
  background: #37adbf;
}
.range-labels .active.selected::before {
  display: none;
}

</style>

<php echo $message; ?>

<script type="text/javascript">
	angular.module("filterApp", []).controller("filterDemo", filterDemo)

function filterDemo() {
  let vm = this;
  vm.ram = "NODATA";
  vm.hdd = "NODATA";
  vm.location = "NODATA";
  vm.storage = 'NODATA';


  vm.names = [{model:'HP DL120G7Intel Xeon E3-1230',ram:'16GBDDR3',hdd:'SAS',location:'Washington D.C.WDC-01',price:'$105.99'},{model:'SP DL120G7Intel Xeon E3-1230',ram:'32GBDDR3',hdd:'SATA',location:'Newyork D.C.WDC-01',price:'$110'}];

  vm.locations = ['AmsterdamAMS-01', 'San FranciscoSFO-12', 'SingaporeSIN-11', 'Washington D.C.WDC-01', 'San FranciscoSFO-12','DallasDAL-10', 'FrankfurtFRA-10','Hong KongHKG-10', 'Newyork D.C.WDC-01'];

  vm.harddiskTypes = ['SAS', 'SATA', 'SSD'];

  vm.filterList = filterList
  
  function filterList(row) {
 
 vm.ram = ($('input[name="ramGroup"]:checked')[0])?$('input[name="ramGroup"]:checked')[0].value:'';

 vm.storage = ($('ul li.active')[0].innerHTML)?$('ul li.active')[0].innerHTML:'';

    if(row.location == vm.location || row.hdd.includes(vm.hdd) || row.hdd.includes(vm.storage) || row.ram.includes(vm.ram)){
    	return true;
    }else{
    	return false;
    }
  };

  function setStorage($event){
  	console.log($event);
  }

}



</script>

<div ng-app="filterApp" class="container" ng-controller="filterDemo as ctrl">
  <h1>Filter Model, HDD, RAM, & Location</h1>
  <hr />

 <div class='form-group'>
        <div class='row'>
           <div class="right-inner-addon col-md-12 ">        
            <div class="range">
			  <input type="range" min="1" max="12" steps="1" value="1" ng-mode="ctrl.hdd" ng-click="ctrl.setStorage($event)">
			</div>
			
		<ul class="range-labels">
		  <li class="active selected">0</li>
		  <li>250GB</li>
		  <li>500GB</li>
		  <li>1TB</li>
		  <li>2TB</li>
		  <li>3TB</li>
		  <li>4TB</li>
		  <li>8TB</li>
		  <li>12TB</li>
		  <li>24TB</li>
		  <li>48TB</li>
		  <li>72TB</li>
		</ul>
           </div>
           </div>
</div>

    <div class='form-group'>
        <div class='row'>
           <div class="right-inner-addon col-md-12">        
            <label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox1" value="2GB" name="ramGroup" ng-model="ctr.ram"> 2GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox2" value="4GB" name="ramGroup" ng-model="ctr.ram1" > 4GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox3" value="8GB" name="ramGroup" ng-model="ctr.ram2"> 8GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox1" value="12GB" name="ramGroup" ng-model="ctr.ram3"> 12GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox2" value="16GB" name="ramGroup" ng-model="ctr.ram4"> 16GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox3" value="24GB" name="ramGroup" ng-model="ctr.ram5"> 24GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox1" value="32GB" name="ramGroup" ng-model="ctr.ram6"> 32GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox2" value="48GB" name="ramGroup" ng-model="ctr.ram7"> 48GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox3" value="64GB" name="ramGroup" ng-model="ctr.ram8"> 64GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox3" value="96GB" name="ramGroup" ng-model="ctr.ram9"> 96GB
			</label>
          </div>
        </div>
    </div>

    <div class='form-group'>
        <div class='row'>
    <div class="right-inner-addon col-md-4 ">        
            <select class="form-control" ng-options="x for x in ctrl.locations" ng-model='ctrl.location'><option value="">--</option></select>
          </div>
         
          <div class="right-inner-addon col-md-4 ">        
            <select class="form-control" ng-options="x for x in ctrl.harddiskTypes" ng-model='ctrl.hdd'>
            <option value="">--</option>
			</select>
          </div>
          </div>
          </div>
        
    <h3>Total Records : </h3>
     <table class="table table-bordered" >
       <tr>
         <th>Model</th>
         <th>RAM</th>
         <th>HDD</th>
         <th>Location</th>
         <th>price</th>
       <tr>
       <tr ng-repeat="item in ctrl.names | filter:ctrl.filterList">
         <td>{{item.model}}</td>
         <td>{{item.ram}}</td>
         <td>{{item.hdd}}</td>
         <td>{{item.location}}</td>
         <td>{{item.price}}</td>
       <tr>
      </table>    
  </form>
  
</div>

<script type="text/javascript">
	var sheet = document.createElement('style'),  
  $rangeInput = $('.range input'),
  prefs = ['webkit-slider-runnable-track', 'moz-range-track', 'ms-track'];

document.body.appendChild(sheet);

var getTrackStyle = function (el) {  
  var curVal = el.value,
      val = (curVal - 1) * 8.9999,
      style = '';
  
  // Set active label
  $('.range-labels li').removeClass('active selected');
  
  var curLabel = $('.range-labels').find('li:nth-child(' + curVal + ')');
  
  curLabel.addClass('active selected');
  curLabel.prevAll().addClass('selected');
  
  // Change background gradient
  for (var i = 0; i < prefs.length; i++) {
    style += '.range {background: linear-gradient(to right, #37adbf 0%, #37adbf ' + val + '%, #fff ' + val + '%, #fff 100%)}';
    style += '.range input::-' + prefs[i] + '{background: linear-gradient(to right, #37adbf 0%, #37adbf ' + val + '%, #b2b2b2 ' + val + '%, #b2b2b2 100%)}';
  }

  return style;
}

$rangeInput.on('input', function () {
  sheet.textContent = getTrackStyle(this);
});

// Change input value on label click
$('.range-labels li').on('click', function () {
  var index = $(this).index();
  
  $rangeInput.val(index + 1).trigger('input');

  
});


$('input[type="checkbox"]').on('change', function() {
    $('input[name="' + this.name + '"]').not(this).prop('checked', false);
});
</script>