<script type="text/javascript">

function csvJSON(csv){

  var lines=csv.split("\n");

  var result = [];

  var headers=lines[0].split(",");

  for(var i=1;i<lines.length;i++){

	  var obj = {};
	  var currentline=lines[i].split(",");

	  for(var j=0;j<headers.length;j++){
		  obj[headers[j]] = currentline[j];
	  }

	  result.push(obj);

  }
  return result;
}


angular.module("filterApp", []).controller("filterDemo", filterDemo)



function filterDemo() {
  let vm = this;
  vm.ram = "NODATA";
  vm.hdd = "NODATA";
  vm.location = "NODATA";
  vm.storage = 'NODATA';
  vm.names = [];


 $.ajax({
        type: "GET",
        url: "LeaseWeb_servers_filters_assignment.csv",
        dataType: "text",
        success: function(data) {
	vm.names = csvJSON(data);
	}
     });


  vm.locations = ['AmsterdamAMS-01', 'San FranciscoSFO-12', 'SingaporeSIN-11', 'Washington D.C.WDC-01', 'San FranciscoSFO-12','DallasDAL-10', 'FrankfurtFRA-10','Hong KongHKG-10', 'Newyork D.C.WDC-01'];

  vm.harddiskTypes = ['SAS', 'SATA', 'SSD'];

  vm.filterList = filterList

	function checkgMatchingRam(ram){
	var notFound = true;
	if(ram){
	for (i=0 ; i< $('input[name="ramGroup"]:checked').length;i++){
		if (ram.indexOf($('input[name="ramGroup"]:checked')[i].value) == 0){
			notFound  = false;
			return true;
		}
	}
}	
	if(notFound){
		return false;
	} 

	}

function checkgMatchingStorage(hdd){
	var notFound = true;
	if(hdd){
	for (i=0 ; i< $('ul li.selected').length;i++){
		if (hdd.indexOf($('ul li.selected')[i].value) == 0){
			notFound  = false;
			return true;
		}
	}
}	
	if(notFound){
		return false;
	} 

	}


  
  function filterList(row) {
		
	    if(vm && row.location == vm.location || (row.hdd && row.hdd.indexOf(vm.hdd) != -1) || checkgMatchingRam(row.ram) || checkgMatchingStorage(row.hdd)){
	    	return true;
	    }else{
	    	return false;
	    }
       };
 
}


</script>



<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Lease Web</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a target="_blank" href="https://github.com/SarveshSK/ServerAppNew.git">Github Link</a></li>
              <li><a target="_blank" href="https://www.linkedin.com/in/sarvesh-kulkarni-0bb4233b/">About Sarvesh</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>



<div ng-app="filterApp" class="container" style="background-color: azure;" ng-controller="filterDemo as ctrl" >
  <h1>Filter Servers with the following search options</h1>
  <hr />


 <div class='form-group'>
<div class="row"><h4> Storage</h4></div>
        <div class='row'>
           <div class="right-inner-addon col-md-12 ">        
            <div class="range">
			  <input type="range" min="1" max="12" steps="1" value="1" ng-model="ctrl.hdd">
			</div>
			
		<ul class="range-labels">
		  <li class="active selected">0</li>
		  <li>250GB</li>
		  <li>500GB</li>
		  <li>1TB</li>
		  <li>2TB</li>
		  <li>3TB</li>
		  <li>4TB</li>
		  <li>8TB</li>
		  <li>12TB</li>
		  <li>24TB</li>
		  <li>48TB</li>
		  <li>72TB</li>
		</ul>
           </div>
           </div>
</div>

    <div class='form-group'>
<div class="row"><h4> Ram</h4></div>
        <div class='row'>
           <div class="right-inner-addon col-md-12">        
            <label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox1" value="2GB" name="ramGroup"ng-model="ctr.ram1"> 2GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox2" value="4GB" name="ramGroup" ng-model="ctr.ram2"> 4GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox3" value="8GB" name="ramGroup" ng-model="ctr.ram3"> 8GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox1" value="12GB" name="ramGroup" ng-model="ctr.ram4"> 12GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox2" value="16GB" name="ramGroup" ng-model="ctr.ram5"> 16GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox3" value="24GB" name="ramGroup" ng-model="ctr.ram6"> 24GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox1" value="32GB" name="ramGroup" ng-model="ctr.ram7"> 32GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox2" value="48GB" name="ramGroup" ng-model="ctr.ram8"> 48GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox3" value="64GB" name="ramGroup" ng-model="ctr.ram9"> 64GB
			</label>
			<label class="checkbox-inline big-checkbox">
  				<input type="checkbox" id="inlineCheckbox3" value="96GB" name="ramGroup" ng-model="ctr.ram10"> 96GB
			</label>
          </div>
        </div>
    </div>

    <div class='form-group'>
        <div class='row'>
	<div class="form-group">
   	 <div class="right-inner-addon col-md-4 ">    
	<label class="col-md-4 control-label" for="textinput">Location</label>    
            <select class="form-control" ng-options="x for x in ctrl.locations" ng-model='ctrl.location'><option value="">--</option></select>
          </div>
	</div>

	<div class="form-group">
          <div class="right-inner-addon col-md-4 ">   
	<label class="col-md-4 control-label" for="textinput">HDD Type</label>     
            <select class="form-control" ng-options="x for x in ctrl.harddiskTypes" ng-model='ctrl.hdd'>
            <option value="">--</option>
			</select>
          </div>
</div>
          </div>
          </div>
        
    <h3>Total Records : {{filtered.length }}</h3>
     <table class="table table-bordered" >
       <tr>
         <th>Model</th>
         <th>RAM</th>
         <th>HDD</th>
         <th>Location</th>
         <th>price</th>
       <tr>
       <tr ng-repeat="item in filtered = (ctrl.names | filter:ctrl.filterList)">
         <td>{{item.model}}</td>
         <td>{{item.ram}}</td>
         <td>{{item.hdd}}</td>
         <td>{{item.location}}</td>
         <td>{{item.price | currency}}</td>
       <tr>
      </table>    
	<tbody ng-if="filtered.length == 0"> Please Enter Your Search Criteria Above <tbody>
  </form>
  
</div>

<script type="text/javascript">
	var sheet = document.createElement('style'),  
  $rangeInput = $('.range input'),
  prefs = ['webkit-slider-runnable-track', 'moz-range-track', 'ms-track'];

document.body.appendChild(sheet);

var getTrackStyle = function (el) {  
  var curVal = el.value,
      val = (curVal - 1) * 8.9999,
      style = '';
  
  // Set active label
  $('.range-labels li').removeClass('active selected');
  
  var curLabel = $('.range-labels').find('li:nth-child(' + curVal + ')');
  
  curLabel.addClass('active selected');
  curLabel.prevAll().addClass('selected');
  
  // Change background gradient
  for (var i = 0; i < prefs.length; i++) {
    style += '.range {background: linear-gradient(to right, #37adbf 0%, #37adbf ' + val + '%, #fff ' + val + '%, #fff 100%)}';
    style += '.range input::-' + prefs[i] + '{background: linear-gradient(to right, #37adbf 0%, #37adbf ' + val + '%, #b2b2b2 ' + val + '%, #b2b2b2 100%)}';
  }

  return style;
}

$rangeInput.on('input', function () {
  sheet.textContent = getTrackStyle(this);
});

// Change input value on label click
$('.range-labels li').on('click', function () {
  var index = $(this).index();
  
  $rangeInput.val(index + 1).trigger('input');

  
});
</script>